default: &default
  adapter: mysql2
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root

development:
  <<: *default
  database: sharegrid_onsite_dev

test:
  <<: *default
  database: sharegrid_onsite_test
